"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOneProfileArgs = exports.UpdateOneProfileArgs = exports.UpdateManyProfileArgs = exports.GroupByProfileArgs = exports.FindUniqueProfileArgs = exports.FindManyProfileArgs = exports.FindFirstProfileArgs = exports.DeleteOneProfileArgs = exports.DeleteManyProfileArgs = exports.CreateOneProfileArgs = exports.CreateManyProfileArgs = exports.AggregateProfileArgs = void 0;
var AggregateProfileArgs_1 = require("./AggregateProfileArgs");
Object.defineProperty(exports, "AggregateProfileArgs", { enumerable: true, get: function () { return AggregateProfileArgs_1.AggregateProfileArgs; } });
var CreateManyProfileArgs_1 = require("./CreateManyProfileArgs");
Object.defineProperty(exports, "CreateManyProfileArgs", { enumerable: true, get: function () { return CreateManyProfileArgs_1.CreateManyProfileArgs; } });
var CreateOneProfileArgs_1 = require("./CreateOneProfileArgs");
Object.defineProperty(exports, "CreateOneProfileArgs", { enumerable: true, get: function () { return CreateOneProfileArgs_1.CreateOneProfileArgs; } });
var DeleteManyProfileArgs_1 = require("./DeleteManyProfileArgs");
Object.defineProperty(exports, "DeleteManyProfileArgs", { enumerable: true, get: function () { return DeleteManyProfileArgs_1.DeleteManyProfileArgs; } });
var DeleteOneProfileArgs_1 = require("./DeleteOneProfileArgs");
Object.defineProperty(exports, "DeleteOneProfileArgs", { enumerable: true, get: function () { return DeleteOneProfileArgs_1.DeleteOneProfileArgs; } });
var FindFirstProfileArgs_1 = require("./FindFirstProfileArgs");
Object.defineProperty(exports, "FindFirstProfileArgs", { enumerable: true, get: function () { return FindFirstProfileArgs_1.FindFirstProfileArgs; } });
var FindManyProfileArgs_1 = require("./FindManyProfileArgs");
Object.defineProperty(exports, "FindManyProfileArgs", { enumerable: true, get: function () { return FindManyProfileArgs_1.FindManyProfileArgs; } });
var FindUniqueProfileArgs_1 = require("./FindUniqueProfileArgs");
Object.defineProperty(exports, "FindUniqueProfileArgs", { enumerable: true, get: function () { return FindUniqueProfileArgs_1.FindUniqueProfileArgs; } });
var GroupByProfileArgs_1 = require("./GroupByProfileArgs");
Object.defineProperty(exports, "GroupByProfileArgs", { enumerable: true, get: function () { return GroupByProfileArgs_1.GroupByProfileArgs; } });
var UpdateManyProfileArgs_1 = require("./UpdateManyProfileArgs");
Object.defineProperty(exports, "UpdateManyProfileArgs", { enumerable: true, get: function () { return UpdateManyProfileArgs_1.UpdateManyProfileArgs; } });
var UpdateOneProfileArgs_1 = require("./UpdateOneProfileArgs");
Object.defineProperty(exports, "UpdateOneProfileArgs", { enumerable: true, get: function () { return UpdateOneProfileArgs_1.UpdateOneProfileArgs; } });
var UpsertOneProfileArgs_1 = require("./UpsertOneProfileArgs");
Object.defineProperty(exports, "UpsertOneProfileArgs", { enumerable: true, get: function () { return UpsertOneProfileArgs_1.UpsertOneProfileArgs; } });
